[package]
name = "fourth_bridge"
version = "0.1.3"
edition = "2024"

[dependencies]
dbus = "0.9.9"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yml = "0.0.12"
urlencoding = "2.1.3"
