
projects:
  -
    name: Project 1
    code: p1

    vscode:
      - '{foo}'

    obsidian: 2025-08-25 - Some Note

    terminal:
      - '{foo}'

    # Dirs defined here are scoped to each project
    dirs:
      foo: '{bar}/some/folder/'
  -
    name: Project 2
    code: p2

    vscode:
      - '{bar}'

    zed:
      - '{bar}'

    obsidian: 2025-08-25 - Some Other Note


dirs:
  home: /home/user
  bar:  '{home}/bar/'
  baz:  '{home}/baz'
